# Site settings
title: Samaa Ashley Kouyele — Portfolio
email: samaa.kouyele@example.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio de Samaa Ashley Kouyele, étudiante en Data Science à Centrale
  Lille : parcours, projets académiques, expériences et compétences.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Samaa Ashley Kouyele
email: samaa.kouyele@example.com
github_username: Sam84-TECH
linkedin_username: samaa-ashley-kouyele
copyright: Samaa Ashley Kouyele

# Build settings
markdown: kramdown
